// DummyData.jsx

const dummyLeadsData = [
    {
      leadID: 101,
      leadName: "John Doe",
      leadSource: "Email",
      leadStatus: "Interested",
      performanceMetric: 75,
      conversionRate: 15,
      sales: 5000,
      region: "North America",
      date: "2024-01-15",
    },
    {
      leadID: 102,
      leadName: "Jane Smith",
      leadSource: "Social Media",
      leadStatus: "Contacted",
      performanceMetric: 60,
      conversionRate: 20,
      sales: 3200,
      region: "Europe",
      date: "2024-02-12",
    },
    {
      leadID: 103,
      leadName: "Mike Johnson",
      leadSource: "Referral",
      leadStatus: "Qualified",
      performanceMetric: 90,
      conversionRate: 10,
      sales: 7600,
      region: "Asia",
      date: "2024-03-10",
    },
    {
      leadID: 104,
      leadName: "Emily Davis",
      leadSource: "Website",
      leadStatus: "Lost",
      performanceMetric: 50,
      conversionRate: 5,
      sales: 1200,
      region: "Australia",
      date: "2024-04-18",
    },
    {
      leadID: 105,
      leadName: "Alex Carter",
      leadSource: "Cold Call",
      leadStatus: "Closed",
      performanceMetric: 80,
      conversionRate: 25,
      sales: 9800,
      region: "South America",
      date: "2024-05-22",
    },
    {
      leadID: 106,
      leadName: "Chris Green",
      leadSource: "Email",
      leadStatus: "Qualified",
      performanceMetric: 85,
      conversionRate: 18,
      sales: 6700,
      region: "Europe",
      date: "2024-06-30",
    },
    {
      leadID: 107,
      leadName: "Nina White",
      leadSource: "Social Media",
      leadStatus: "Interested",
      performanceMetric: 72,
      conversionRate: 12,
      sales: 4200,
      region: "North America",
      date: "2024-07-15",
    },
    {
      leadID: 108,
      leadName: "Tom Black",
      leadSource: "Referral",
      leadStatus: "Closed",
      performanceMetric: 95,
      conversionRate: 30,
      sales: 15000,
      region: "Asia",
      date: "2024-08-19",
    },
    {
      leadID: 109,
      leadName: "Sara Brown",
      leadSource: "Website",
      leadStatus: "Lost",
      performanceMetric: 55,
      conversionRate: 8,
      sales: 2300,
      region: "Australia",
      date: "2024-09-10",
    },
    {
      leadID: 110,
      leadName: "Luke Wilson",
      leadSource: "Cold Call",
      leadStatus: "Qualified",
      performanceMetric: 78,
      conversionRate: 14,
      sales: 8700,
      region: "South America",
      date: "2024-10-01",
    },
  ];
  
  export default dummyLeadsData;
  